server:
  port: 80
  servlet:
    session:
      timeout: 300000000000s     
  
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
      resolve-lazily: false

        
mybatis:
  config-location: classpath:mybatisConfig.xml    
  
      
     
