server:
  port: 80
  
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
      resolve-lazily: false

#mybatis的配置文件在那里    
mybatis:
  config-location: classpath:mybatisConfig.xml    
      
     
